// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePlayer(arg1, arg2) {
  return window['go']['entitys']['PlayerManager']['CreatePlayer'](arg1, arg2);
}
