// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entitys} from '../models';

export function CreatePlayer(arg1:string,arg2:string):Promise<entitys.Player>;

export function GetExamplePlayers():Promise<Array<entitys.Player>>;
