// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entitys} from '../models';

export function CreateTournament(arg1:string,arg2:boolean,arg3:Array<entitys.Player>):Promise<entitys.Tournament_Direct_Elimination>;

export function GetTournamentById(arg1:string):Promise<entitys.Tournament_Direct_Elimination>;

export function UpdateTournament(arg1:string,arg2:string,arg3:{[key: string]: any}):Promise<entitys.Tournament_Direct_Elimination>;
