// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTournament(arg1) {
  return window['go']['entitys']['TournamentManager']['CreateTournament'](arg1);
}

export function SetInitialMatches(arg1) {
  return window['go']['entitys']['TournamentManager']['SetInitialMatches'](arg1);
}

export function TestTournament() {
  return window['go']['entitys']['TournamentManager']['TestTournament']();
}
