// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entitys} from '../models';

export function CreateTournament(arg1:Array<entitys.Player>):Promise<entitys.Tournament>;

export function SetInitialMatches(arg1:entitys.Tournament):Promise<entitys.Tournament>;

export function TestTournament():Promise<entitys.Tournament>;
