// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTournament(arg1, arg2, arg3) {
  return window['go']['entitys']['TournamentManager']['CreateTournament'](arg1, arg2, arg3);
}

export function GetTournamentById(arg1) {
  return window['go']['entitys']['TournamentManager']['GetTournamentById'](arg1);
}

export function UpdateTournament(arg1, arg2, arg3) {
  return window['go']['entitys']['TournamentManager']['UpdateTournament'](arg1, arg2, arg3);
}
